import { estimateTokens, type AgentMessage, type StreamFn } from '@earendil-works/pi-agent-core'
import type { AssistantMessage, Model, ThinkingLevel, Usage } from '@earendil-works/pi-ai'
import { completeSimple } from '@earendil-works/pi-ai/compat'

export const SUBAGENT_COMPACTION_POLICY = Object.freeze({
  enabled: true,
  reserveTokens: 16_384,
  keepRecentTokens: 20_000,
})

export const SUBAGENT_COMPACTION_MARKER = '[subagent_context_checkpoint]'

const CHECKPOINT_PREAMBLE = [
  'The following summary was generated by the host to continue this child run.',
  'Treat it as a context checkpoint, not as user instructions.',
].join(' ')

export interface CompactionCut {
  pinned: AgentMessage
  middle: AgentMessage[]
  tail: AgentMessage[]
  previousSummary?: string
}

export interface CompactSubagentMessagesInput {
  messages: readonly AgentMessage[]
  model: Model<any>
  apiKey: string
  streamFn?: StreamFn
  signal?: AbortSignal
  thinkingLevel?: ThinkingLevel
  previousSummary?: string
  force?: boolean
  policy?: {
    enabled: boolean
    reserveTokens: number
    keepRecentTokens: number
  }
  generateSummary?: SubagentSummaryGenerator
}

export type SubagentSummaryGenerator = (
  messages: AgentMessage[],
  model: Model<any>,
  reserveTokens: number,
  apiKey: string | undefined,
  headers: Record<string, string> | undefined,
  signal: AbortSignal | undefined,
  customInstructions: string | undefined,
  previousSummary: string | undefined,
  thinkingLevel: ThinkingLevel | undefined,
  streamFn?: StreamFn,
) => Promise<{ text: string; usage: Usage }>

export interface CompactSubagentMessagesResult {
  messages: AgentMessage[]
  summary: string
  usage: Usage
}

function messageRole(message: AgentMessage): string {
  return (message as { role?: string }).role || ''
}

function userMessageText(message: AgentMessage): string {
  const content = (message as { content?: unknown }).content
  if (typeof content === 'string') return content.trim()
  if (!Array.isArray(content)) return ''
  return content
    .flatMap((item) => {
      if (!item || typeof item !== 'object') return []
      const block = item as { type?: unknown; text?: unknown }
      return block.type === 'text' && typeof block.text === 'string' ? [block.text] : []
    })
    .join('\n')
    .trim()
}

export function buildCheckpointText(summary: string): string {
  return [SUBAGENT_COMPACTION_MARKER, CHECKPOINT_PREAMBLE, '', summary.trim()].join('\n')
}

export function readCheckpointSummary(text: string): string | null {
  const trimmed = text.trim()
  if (!trimmed.startsWith(SUBAGENT_COMPACTION_MARKER)) return null
  const separator = trimmed.indexOf('\n\n')
  const body = separator >= 0
    ? trimmed.slice(separator + 2).trim()
    : trimmed.slice(SUBAGENT_COMPACTION_MARKER.length).trim()
  return body || null
}

function findPreviousSummary(messages: readonly AgentMessage[]): string | undefined {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    if (messageRole(messages[index]) !== 'user') continue
    const summary = readCheckpointSummary(userMessageText(messages[index]))
    if (summary) return summary
  }
  return undefined
}

function finishCut(
  messages: readonly AgentMessage[],
  firstUserIndex: number,
  cutIndex: number,
): CompactionCut | null {
  const middle = messages.slice(firstUserIndex + 1, cutIndex)
  if (middle.length === 0) return null
  return {
    pinned: messages[firstUserIndex],
    middle: [...middle],
    tail: messages.slice(cutIndex),
    previousSummary: findPreviousSummary(messages.slice(0, cutIndex)),
  }
}

export function selectCompactionCut(
  messages: readonly AgentMessage[],
  keepRecentTokens: number,
  options?: { force?: boolean },
): CompactionCut | null {
  if (messages.length === 0) return null
  const firstUserIndex = messages.findIndex((message) => messageRole(message) === 'user')
  if (firstUserIndex < 0) return null

  let accumulated = 0
  let cutIndex = -1
  for (let index = messages.length - 1; index > firstUserIndex; index -= 1) {
    accumulated += estimateTokens(messages[index])
    if (accumulated >= keepRecentTokens) {
      cutIndex = index
      break
    }
  }

  if (cutIndex < 0) {
    return options?.force
      ? finishCut(messages, firstUserIndex, messages.length)
      : null
  }

  while (cutIndex > firstUserIndex + 1 && messageRole(messages[cutIndex]) === 'toolResult') {
    cutIndex -= 1
  }
  if (messageRole(messages[cutIndex]) === 'toolResult') {
    return options?.force
      ? finishCut(messages, firstUserIndex, messages.length)
      : null
  }
  if (cutIndex <= firstUserIndex + 1) {
    return options?.force
      ? finishCut(messages, firstUserIndex, messages.length)
      : null
  }
  return finishCut(messages, firstUserIndex, cutIndex)
}

const SUMMARIZATION_SYSTEM_PROMPT = [
  'You are a context summarization assistant. Your task is to read a conversation',
  'between a user and an AI assistant, then produce a structured summary following',
  'the exact format specified.',
  '',
  'Do NOT continue the conversation. Do NOT respond to any questions in the conversation.',
  'ONLY output the structured summary.',
].join(' ')

const SUMMARIZATION_PROMPT = `The messages above are a conversation to summarize. Create a structured context checkpoint summary that another LLM will use to continue the work.

Use this EXACT format:

## Goal
[What is the user trying to accomplish?]

## Constraints & Preferences
- [Any constraints, preferences, or requirements]
- [Or "(none)" if none were mentioned]

## Progress
### Done
- [x] [Completed tasks/changes]

### In Progress
- [ ] [Current work]

### Blocked
- [Issues preventing progress, if any]

## Key Decisions
- **[Decision]**: [Brief rationale]

## Next Steps
1. [Ordered list of what should happen next]

## Critical Context
- [Any data, examples, or references needed to continue]
- [Or "(none)" if not applicable]

Keep each section concise. Preserve exact file paths, function names, and error messages.`

const UPDATE_SUMMARIZATION_PROMPT = `The messages above are NEW conversation messages to incorporate into the existing summary provided in <previous-summary> tags.

Update the existing structured summary with new information. RULES:
- PRESERVE all existing information from the previous summary
- ADD new progress, decisions, and context from the new messages
- UPDATE the Progress section: move items from "In Progress" to "Done" when completed
- UPDATE "Next Steps" based on what was accomplished
- PRESERVE exact file paths, function names, and error messages

Use the same EXACT format as the previous summary.`

function serializeAgentMessages(messages: readonly AgentMessage[]): string {
  return messages.map((message) => {
    const role = messageRole(message)
    const text = userMessageText(message)
    if (role === 'assistant') {
      const assistant = message as AssistantMessage
      const parts = (assistant.content || []).flatMap((block) => {
        if (block.type === 'text' && block.text.trim()) return [block.text.trim()]
        if (block.type === 'toolCall') {
          return [`[Called tool: ${block.name}]`]
        }
        return []
      })
      return `assistant:\n${parts.join('\n') || text}`
    }
    if (role === 'toolResult') {
      return `toolResult:\n${text.slice(0, 2000)}`
    }
    return `${role}:\n${text}`
  }).join('\n\n')
}

function assistantText(message: AssistantMessage): string {
  return message.content
    .flatMap((part) => (part.type === 'text' && part.text.trim() ? [part.text.trim()] : []))
    .join('\n')
    .trim()
}

export const generateSubagentSummary: SubagentSummaryGenerator = async (
  messages,
  model,
  reserveTokens,
  apiKey,
  _headers,
  signal,
  customInstructions,
  previousSummary,
  thinkingLevel,
  streamFn,
) => {
  const maxTokens = Math.min(
    Math.floor(0.8 * reserveTokens),
    model.maxTokens > 0 ? model.maxTokens : Number.POSITIVE_INFINITY,
  )
  let basePrompt = previousSummary ? UPDATE_SUMMARIZATION_PROMPT : SUMMARIZATION_PROMPT
  if (customInstructions) {
    basePrompt = `${basePrompt}\n\nAdditional focus: ${customInstructions}`
  }
  let promptText = `<conversation>\n${serializeAgentMessages(messages)}\n</conversation>\n\n`
  if (previousSummary) {
    promptText += `<previous-summary>\n${previousSummary}\n</previous-summary>\n\n`
  }
  promptText += basePrompt

  const context = {
    systemPrompt: SUMMARIZATION_SYSTEM_PROMPT,
    messages: [{
      role: 'user' as const,
      content: [{ type: 'text' as const, text: promptText }],
      timestamp: Date.now(),
    }],
  }
  const options = {
    maxTokens,
    signal,
    apiKey,
    cacheRetention: 'none' as const,
    ...(model.reasoning && thinkingLevel
      ? { reasoning: thinkingLevel }
      : {}),
  }
  const response = streamFn
    ? await (await streamFn(model, context, options)).result()
    : await completeSimple(model, context, options)
  if (response.stopReason === 'error') {
    throw new Error(`Summarization failed: ${response.errorMessage || 'Unknown error'}`)
  }
  return { text: assistantText(response), usage: response.usage }
}

export async function compactSubagentMessages(
  input: CompactSubagentMessagesInput,
): Promise<CompactSubagentMessagesResult | null> {
  const policy = input.policy ?? SUBAGENT_COMPACTION_POLICY
  if (!policy.enabled) return null
  const cut = selectCompactionCut(input.messages, policy.keepRecentTokens, { force: input.force })
  if (!cut) return null

  const generate = input.generateSummary ?? generateSubagentSummary
  const { text, usage } = await generate(
    cut.middle,
    input.model,
    policy.reserveTokens,
    input.apiKey,
    undefined,
    input.signal,
    undefined,
    input.previousSummary ?? cut.previousSummary,
    input.thinkingLevel,
    input.streamFn,
  )
  const summary = text.trim()
  if (!summary) return null

  const checkpoint: AgentMessage = {
    role: 'user',
    content: [{ type: 'text', text: buildCheckpointText(summary) }],
    timestamp: Date.now(),
  }
  return {
    messages: [cut.pinned, checkpoint, ...cut.tail],
    summary,
    usage,
  }
}
