from cadpatterns.ontology.pattern_types import (
    CANONICAL_PATTERN_TYPES,
    DEPRECATED_ALIASES,
    GENERIC_ENCLOSURE_CANDIDATE,
    GENERIC_NETWORK_JUNCTION,
    GENERIC_NETWORK_TERMINAL,
    GENERIC_PATH_NETWORK,
    GENERIC_REPEATED_MOTIF_GROUP,
    GENERIC_SHEET_BOUNDARY_CANDIDATE,
    GENERIC_SYMBOL_LIKE_CLUSTER,
    GENERIC_TABLE_GRID,
    GENERIC_TEXT_BLOCK,
    contains_professional_semantics,
    ensure_canonical_pattern_type,
)
from cadpatterns.ontology.spec_loader import (
    DetectorDeclaration,
    PatternSpec,
    load_builtin_specs,
    load_pattern_spec,
    load_specs,
    pattern_spec_from_mapping,
)

__all__ = [
    "CANONICAL_PATTERN_TYPES",
    "DEPRECATED_ALIASES",
    "DetectorDeclaration",
    "GENERIC_ENCLOSURE_CANDIDATE",
    "GENERIC_NETWORK_JUNCTION",
    "GENERIC_NETWORK_TERMINAL",
    "GENERIC_PATH_NETWORK",
    "GENERIC_REPEATED_MOTIF_GROUP",
    "GENERIC_SHEET_BOUNDARY_CANDIDATE",
    "GENERIC_SYMBOL_LIKE_CLUSTER",
    "GENERIC_TABLE_GRID",
    "GENERIC_TEXT_BLOCK",
    "PatternSpec",
    "contains_professional_semantics",
    "ensure_canonical_pattern_type",
    "load_builtin_specs",
    "load_pattern_spec",
    "load_specs",
    "pattern_spec_from_mapping",
]
