"""Named fields from the three docs/dev THCAD extract catalogs, mapped to inventory ids."""

from __future__ import annotations

from pathlib import Path

from .paths import CATALOG_FILES

# Inventory ids that the catalogs name as extractable columns / keys / tags / apps.
# Kind *values* (wipeout/unparsed/polyline2d) are not separate fields; they live under
# entity.geometry.kind and are called out in completeness prose instead.

CATALOG_FIELD_IDS: set[str] = {
    # entities.jsonl common (字段目录 §1)
    "entity.handle",
    "entity.drawing_handle",
    "entity.runtime_class",
    "entity.managed_type",
    "entity.dxf_name",
    "entity.layer",
    "entity.color",
    "entity.color.index",
    "entity.color.is_by_layer",
    "entity.color.is_by_block",
    "entity.color.name",
    "entity.linetype",
    "entity.lineweight",
    "entity.visible",
    "entity.owner_scope",
    "entity.owner_block_name",
    "entity.owner_handle",
    "entity.block_path",
    "entity.geometry",
    "entity.geometry.kind",
    "entity.bbox",
    "entity.bbox.min",
    "entity.bbox.max",
    "entity.text",
    "entity.attributes",
    "entity.attributes.handle",
    "entity.attributes.tag",
    "entity.attributes.value",
    "entity.attributes.invisible",
    "entity.attributes.position",
    "entity.xdata",
    "entity.extension_dictionary",
    "entity.source",
    "entity.decode_status",
    "entity.custom",
    # geometry keys named in 字段目录 §1 + §11.2
    "entity.geometry.start",
    "entity.geometry.end",
    "entity.geometry.center",
    "entity.geometry.radius",
    "entity.geometry.block_name",
    "entity.geometry.position",
    "entity.geometry.pattern",
    "entity.geometry.pattern_type",
    "entity.geometry.measurement",
    "entity.geometry.is_dynamic",
    # text object keys named in 数据底座选型 (measurement + dimension_text)
    "entity.text.dimension_text",
    "entity.text.measurement",
    "entity.text.contents",
    "entity.text.plain",
    # tables
    "layer.name",
    "layer.handle",
    "layer.off",
    "layer.frozen",
    "layer.locked",
    "layer.color",
    "layer.linetype",
    "linetype.name",
    "linetype.handle",
    "linetype.ascii_description",
    "text_style.name",
    "text_style.handle",
    "text_style.font_file",
    "text_style.big_font_file",
    "text_style.text_size",
    "dim_style.name",
    "dim_style.handle",
    "layout.name",
    "layout.handle",
    "layout.tab_order",
    "layout.model_type",
    "layout.block_handle",
    "reg_app.name",
    "reg_app.handle",
    "block.name",
    "block.handle",
    "block.owner_scope",
    "block.is_layout",
    "block.is_anonymous",
    "block.is_from_xref",
    "block.xref_path",
    "block.has_attribute_definitions",
    "block.entity_count",
    "block.origin",
    # dictionaries.jsonl record + named keys
    "dict.key",
    "dict.object",
    "dict.object.handle",
    "dict.object.runtime_class",
    "dict.object.is_proxy",
    "dict.object.count",
    "dict.object.items",
    "dict_key.PC_BOM_DIC",
    "dict_key.PC_BOMXHRELATEDIC",
    "dict_key.PC_MXBSORTDIC",
    "dict_key.PC_PAPER_DIC",
    "dict_key.PC_CRYPTO_PAPER_DIC",
    "dict_key.PC_CRYPTO_MXBSORTDIC",
    "dict_key.PC_ENCRY_BOM_DIC",
    "dict_key.ACAD_LAYOUT",
    "dict_key.ACAD_DATALINK",
    "dict_key.明细表分列记录",
    # title 30 + record
    "semantic.title.kind",
    "semantic.title.handle",
    "semantic.title.block_name",
    "semantic.title.position",
    "semantic.title.fields",
    "title.产品型号",
    "title.图样名称",
    "title.图样代号",
    "title.比例",
    "title.第几页",
    "title.共几页",
    "title.重量",
    "title.材料标记",
    "title.标记1",
    "title.标记2",
    "title.标记3",
    "title.标记4",
    "title.改版标记1",
    "title.改版标记2",
    "title.改版标记3",
    "title.处数1",
    "title.处数2",
    "title.处数3",
    "title.改版分区1",
    "title.改版分区2",
    "title.改版分区3",
    "title.更改文件号1",
    "title.更改文件号2",
    "title.更改文件号3",
    "title.改版签名1",
    "title.改版签名2",
    "title.改版签名3",
    "title.改版日期1",
    "title.改版日期2",
    "title.改版日期3",
    # bom 8 + record
    "semantic.bom.handle",
    "semantic.bom.position",
    "semantic.bom.xdata",
    "semantic.bom.fields",
    "bom.序号",
    "bom.代号",
    "bom.名称",
    "bom.数量",
    "bom.材料",
    "bom.单重",
    "bom.总重",
    "bom.备注",
    # other PC block tags
    "pc.PC_FJL_BLOCK.日期",
    "pc.PC_FJL_BLOCK.底图总号",
    "pc.PC_FJL_BLOCK.签字",
    "pc.PC_TYDH_BLOCK.图样代号",
    "pc.PC_CSL_BLOCK",
    # xuhao-bom-links
    "link.item.seq",
    "link.item.xuhao_handle",
    "link.item.xuhao_found",
    "link.item.bom_handle",
    "link.item.bom_code",
    "link.item.bom_name",
    "link.item.bom_qty",
    "link.item.bom_material",
    "link.item.dict_key",
    "link.item.recorder_handle",
    "link.item.recorder_class",
    # professional shell
    "semantic.prof.handle",
    "semantic.prof.runtime_class",
    "semantic.prof.layer",
    "semantic.prof.bbox",
    "semantic.prof.xdata",
    "semantic.prof.custom",
    "entity.custom.properties",
    "entity.custom.explode",
    "entity.custom.explode_error",
    # entity xdata apps named in 字段目录 §11.3
    "entity.xdata.TH_POWERPARA",
    "entity.xdata.TH_XDATA_ORDER",
    "entity.xdata.TH_XDATA_CODE",
    "entity.xdata.TH_XDATA_VTYPE",
    "entity.xdata.TH_XDATA_ALIGN",
    "entity.xdata.TH_XDATA_EXPRE",
    "entity.xdata.TH_XDATA_ROWDOWITH",
    "entity.xdata.TH_XDATA_ORIENTION",
    "entity.xdata.TH_XDATA_EDITABLE",
    "entity.xdata.TH_XDATA_ATTDEFHANDLE",
    "entity.xdata.TH_XDATA_REFERENCEVALUE",
    "entity.xdata.TH_XDATA_DEFAULTVALUE",
    "entity.xdata.TH_XUHAO",
    "entity.xdata.TH_EXTENT_XDATA",
    "entity.xdata.TH_FrameText",
    "entity.xdata.GENIUS_GENODEF_13",
    "entity.xdata.GENIUS_GENOBJ-N-FIL_13",
    "entity.xdata.GENIUS_GENOBJ-N-REC_13",
    "entity.xdata.GENIUS_GENREC_14",
    "entity.xdata.AcadCodePageInfo",
    "entity.xdata.CAXA_DRAFT_TXTSCALE",
    "entity.xdata.MARUIYUN",
    # drawing.json / report mentioned as files, few keys named
    "drawing.drawing_id",
    "report.entity_count",
    "report.proxy_count",
    "report.type_counts",
}


def catalog_paths() -> list[Path]:
    return list(CATALOG_FILES)


def split_against_inventory(inv_ids: set[str]) -> dict[str, list[str]]:
    catalog = set(CATALOG_FIELD_IDS)
    both = sorted(catalog & inv_ids)
    only_catalog = sorted(catalog - inv_ids)
    only_data = sorted(inv_ids - catalog)
    return {
        "both": both,
        "only_catalog": only_catalog,
        "only_data": only_data,
    }
