import type { SkillPackMetadata } from './backend-api'

// This file is generated by scripts/generate-skill-pack-metadata.mjs.
export const SKILL_PACK_METADATA: SkillPackMetadata = {
  skill_pack_version: '0.8.20',
  skill_pack_checksum: '57fa5f1fa39bc5b9cef8f656e8e64efa06c941f62d5772bd12bf1bd5db7b3987',
  built_at: '2026-08-23T18:25:25.783Z',
}
